name: Asciidoctor Action Test
on:
    push:
        branches:
            - main
        paths:
            - "doc/**"
jobs:
    asciidoc-to-html:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v2

            - name: Install Asciidoctor
              run: sudo apt-get install -y asciidoctor
